default:
  image: aruw/mcb-2020-gitlab-ci:2021-06-02.1

.default_only: &default_only
  - merge_requests
  - master
  - develop
  - schedules

Build all examples:
  only: *default_only
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./build_all_targets.sh

"Policy Checks":
  only: *default_only
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - python3 ./taproot-scripts/check_license_headers.py
        -p taproot-examples
        -o "Advanced Robotics at the University of Washington"
        -i './taproot-scripts/**/*' './taproot/**/*'
